project:
  type: website

website:
  title: "David Niño"
  favicon: "dimension.png"
  navbar:
    background: "#1A2E40"
    foreground: "#FDFEFE"
    right:
      - text: "Curriculum Vitae"
        file: cv.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "BioEpi Insights"
        file: bioepi.qmd
      - text: "Photos"
        file: photos.qmd
  page-footer:
    background: "#ECF0F1"
    foreground: "#2C3E50"
    center: 
      - icon: github
        href: https://github.com/
      - icon: google
        href: https://scholar.google.com/citations?user=igCiJo0AAAAJ&hl=es
    right: |
      This blog is developed by David Niño-Torres using [Quarto](https://quarto.org/), an open-source scientific and technical publishing system.
    left: |
      Supported by [![](https://posit.co/wp-content/themes/Posit/assets/images/posit-logo-2024.svg){fig-alt="Posit" width=65px}](https://posit.co/)

format:
  html:
    theme: Morph
    mainfont: "sans-serif"
    monofont: "sans-serif"
    fontsize: 0.9rem
    fontcolor: "#2C3E50"
    linkcolor: "#7D3C98"
    backgroundcolor: "#FDFEFE"
    toc: true
    toc-depth: 2
    css: styles.css
editor: visual


# header {
#   border-bottom: 1px solid #ccc;
# }

